### ISSUE TITLE
Relax parOneOf and parOneOfMap constraints

### ISSUE THREAD

**Issue by natefaubion** [purescript/purescript-parallel#23]
They require `Alternative`, which `Aff` does not satisfy. And since `Aff` is one of the only interesting things that implements `Parallel`, I feel like we should relax them to `Applicative` + `Plus`.

**Comment by paf31** [comment]
Didn't we discuss this before? I thought we decided there were useful things you could prove only with `Alternative`? Anyway, what does it gain us to change to `Applicative` and `Plus`? Isn't `Aff` an `Alternative`?

**Comment by natefaubion** [comment]
No, it does not satisfy the Alternative laws

**Comment by natefaubion** [comment]
Or at least, it doesn't have an instance. Maybe I was to aggressive when removing bad instances in Aff 4? I thought I remember it failing to be an Alternative for some reason.

**Comment by natefaubion** [comment]
ParAff is the one with the Alternative instance, duh.
