### ISSUE TITLE
Is it possible to relax constraint from `Monad` to `Applicative` in `Parallel` class?

### ISSUE THREAD

**Issue by paluh** [purescript/purescript-parallel#24]
[I have an `Applicative`](https://github.com/paluh/purescript-polyform/blob/master/src/Polyform/Validator.purs#L21) (which is not a `Monad`) and [I have another `Applicative`](https://github.com/paluh/purescript-polyform/blob/master/src/Polyform/Validator/Par.purs#L15) which with additional constraints provides parallel apply for my initial type. It seems that this is the purpose of `Parallel` class - to define such a relation between types.
If I understand it correctly `Parallel` requires me to provide `Monad` instance for my "non parallel type". Why is this the case? Wouldn't it be enough to just require an `Applicative` instance?

**Comment by garyb** [comment]
I don't know if there is a good reason not to do this - it seems reasonable, but I guess the idea is if there's a `Monad` instance then it is _required_ to behave sequentially due to `ap = apply`.

Any thoughts @paf31, @natefaubion?

**Comment by natefaubion** [comment]
Considering there are no laws...

**Comment by masaeedu** [comment]
Would you folks take a PR implementing this? Or would the resulting breakage be too large?
