### ISSUE TITLE
Port Parallel guide to this repo

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/purescript-parallel#30]
In my effort for doing jordanmartinez/purescript-jordans-reference#472, I would like to port two files to this repo:
- [Syntax](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/22-Projects/src/01-Libraries/Parallel/01-Syntax.purs), which covers the main API here and a general idea for how it works.
- [Instances for Parallel](https://github.com/JordanMartinez/purescript-jordans-reference/blob/latestRelease/22-Projects/src/01-Libraries/Parallel/11-Instance-for-Parallel.purs), which covers how to implement a Parallel instance for a ReaderT-based monad for one's application.

What issues, if any, would arise if I do this?

**Comment by hdgarrood** [comment]
Sounds good to me! Since it's all code, I think adding it to an `examples` directory and linking to it from the readme would probably make the most sense.

**Comment by JordanMartinez** [comment]
Sounds good! I'll try to get to this tonight.

**Comment by JordanMartinez** [comment]
This can be closed as the code was ported to the cookbook repo.
